### PR TITLE
Staff Profiles page removal, as this is now replaced by Springshare

### PR DESCRIPTION
**Pull request by murny**
@nnunn has mentioned that Staff Profiles pages in library-cms is no longer needed as it's been replaced by Springshare.

This pull request is for cleaning up all this code (route entry, models, controller, views, some of the gems associated with it (friendly ID) and ultimately dropping the tables for this).

### CODE REVIEW

**Review by nnunn — APPROVED** [review]
LGTM!

**Comment by nnunn** [comment]
The new staff directory app is now up at https://guides.library.ualberta.ca/az/library-staff-directory - it would be good to have a redirect from https://library.ualberta.ca/staff to the new directory. Also, sorry if I reviewed your changes too early. I'm a bit confused about this workflow.

**Review by pgwillia — DISMISSED** [review]

**Comment by nnunn** [comment]
All look great to me! Thanks for all your work.

**Review by nnunn — APPROVED** [review]
LGTM!

**Pull request merged**
